language: java
sudo: false
deploy:
  provider: releases
  file: build/libs/xlr-pagerduty-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-pagerduty-plugin
  api_key:
    secure: bc9bi2i88n5CBxlmUYKLokeLWsTnPrSl0xbLHUcQjP1+rwny3GBR5CQ2dGkkg4W3luHnQ2LqfHfiDGzYu4PPyLtuXV1hd5R6qt4im+GtIYi4BSRuJicEG4+WXQEdhT6hAJKSc8+js/NmZm8Y+vuDwH8vSWAhBCs7taBEWibOIxz+OoPWMuO1ISbCu7DKsfu9YZQ9cnNv1fjaIdgyqntPUs4MSj3t53DaKQUcP9VFgvRjf86T2kJOHV1wQVXDWTC7m5VirZuPfWVOIXBB4QleP1AJUj+OP3CN49HxShThfvMw+OlWfYKy72Ojow0YofJqipOvotqLHELKNk8PtGj16By9ignoXZSUABmLr+P+cFkYlwkYVBt5dcx99lXlI9Lj3+QUMo8qj3lYaQdOFi6ESt64CCXjl0Y8m+wAA8OV7yaPpTPAOV8ulwN4EWrU5NVnedSnS0zvrT2b2HiZHFTfYX5pCqt1697A2XiWCWeKmcAVdAC9Li2AcWa69TF0lYSgYj5NyRpR9QeksUVL1RIbFjQyUYdqPTEh5oNv0zyzUYWGcY+FStjchRVjRZydOTNDYx1hBUXNRLfHCYEgKT2lQLFdnexT7MEFvxDzXi0ABzb27pWwsGE0o2owpGkQ4+7RtH4M5vslKJ6PLvgRQmHBERyDj4YBeB2W9MheD/upRLw=
notifications:
  pagerduty:
    rooms:
      secure: VEAS0RDkNKkyPobVZKcbR484Tzhing7oNon/0qoztBCZ7+XlsP9yVqDrlceqRd0r2vkPKV5tKnReMMDY7gQVAbbubzjtLoW6TpuI+DJMQOs7TRHmMT681RUGzrvaRo/pQFykNbQ2u54TqGxJw/RzezQnsNqlTdmMp+ZlHR1tm+DQ5tVpdzE4N+5e6VyFwhMaVJVdK8LbX9tLjB8fr8vYS9hI1aHkV8s61DfW66q8Ogs0G5xkIRw4B4nRJb58lnCWnyJrxVyt3JIXfQwlUwMDPI719qs3Th6gJwrRrak7HFIaYhy3RIvaUMCI6yiafUIPg/Nzaqd02HTBhM1Qx8aU/2bvNM3vgQjAnrIG9GM01TQnNjSzPDSPNdyD7OcyY0KOH7NLS6DEbxNcIytRrrsZFXq4TM00PgmGlEft5w4oPUUhXCewaJLlbsgC1Cmk9BCv4qJNfbxCrkkuA7g9ap2PFoKmnZ9HbQGyqxQ1X/fI0g5I4S5nISig+wljgfMBI7VgbofV+pp/QVvR97vhmmiXX8jAj+X2YRsaxYERUisnnJO5rYyLPOn9tCFHJphYQIlHIIuH7j5V9pK0BYt8ZLZtSb61OBkbxz8yJyG0BGcnYan8sIovo/8SpFgE5UUAfY+4mqGP4xhM0knTI+d9lMmkM6I1trRswB+1Vyl7ATH+eXg=
