language: java
sudo: false
deploy:
  provider: releases
  file: build/libs/xlr-pagerduty-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-pagerduty-plugin
  api_key:
    secure:
      secure: SVwCRjxFbR2OMMFgkRRivSEfD9mDiaP+cR+eJwgRiWAMXD0yt0GaZMdP/Gq0DX8lnqqoSfIPGsxbQXMObi+a5wQcwE+ld19ou10TvKoe4CXz6XQtLmcJz9caINvh3TWFPyx66+tLJsOhDoDTcjo8TKJ77BfXgODN/cg1Laim38slGi6Ngp9aPpQY5PzLD7o9nrPR2KdqE+onq38rO7x2y8ssUAQH4Dlays+C1zXUnbwoGKO7Jg2E/kaUd3TtQynjr46azaWa5sOfnSoZ8ui/J0i5y/L0i3pDMsQMRNsCiH65UmJDuCu+CaEEes8kqHJTfAWlc3DZStFYBmcXNiGAP+avKJPgTuk0ZxMekKeROFkcEgu4aNn7yanCEhv8YojRT4Y3gZOZid3XaX1GEUMf6s0faIS2AQgBUDW/JtkNRNYerDMAWIwJ8NN+c4fRq5FhfRyGdQykdq7e//tBqs1WF8npFstNR5fgZ2D4Rnxe2lOD1DsOZvamYaNk6hrrQ1Qh0rl9Q36x+78+aQlUqT++u4IhBv4hbw/gh144HAfPmWUp/wmLf3/Rmu6Mqatgs8QF2exmJCpqQ0C9eMaOJwx2HO98iSZdaafRGXxVHJYX1wuWKevyGDvTNSTwp3rkcmqzA/41/R6+8P2HoHAMKNi6Cvm9M3KpmNcQDrJwy6wv5Xw=
notifications:
  hipchat:
    rooms:
      secure: VEAS0RDkNKkyPobVZKcbR484Tzhing7oNon/0qoztBCZ7+XlsP9yVqDrlceqRd0r2vkPKV5tKnReMMDY7gQVAbbubzjtLoW6TpuI+DJMQOs7TRHmMT681RUGzrvaRo/pQFykNbQ2u54TqGxJw/RzezQnsNqlTdmMp+ZlHR1tm+DQ5tVpdzE4N+5e6VyFwhMaVJVdK8LbX9tLjB8fr8vYS9hI1aHkV8s61DfW66q8Ogs0G5xkIRw4B4nRJb58lnCWnyJrxVyt3JIXfQwlUwMDPI719qs3Th6gJwrRrak7HFIaYhy3RIvaUMCI6yiafUIPg/Nzaqd02HTBhM1Qx8aU/2bvNM3vgQjAnrIG9GM01TQnNjSzPDSPNdyD7OcyY0KOH7NLS6DEbxNcIytRrrsZFXq4TM00PgmGlEft5w4oPUUhXCewaJLlbsgC1Cmk9BCv4qJNfbxCrkkuA7g9ap2PFoKmnZ9HbQGyqxQ1X/fI0g5I4S5nISig+wljgfMBI7VgbofV+pp/QVvR97vhmmiXX8jAj+X2YRsaxYERUisnnJO5rYyLPOn9tCFHJphYQIlHIIuH7j5V9pK0BYt8ZLZtSb61OBkbxz8yJyG0BGcnYan8sIovo/8SpFgE5UUAfY+4mqGP4xhM0knTI+d9lMmkM6I1trRswB+1Vyl7ATH+eXg=
